spring:
  application:
    name: ai-code-helper
  profiles:
    active: local

langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen3.5-27b
        api-key: ${DASH_SCOPE_API_KEY}
      embedding-model:
        model-name: text-embedding-v3
        api-key: ${DASH_SCOPE_API_KEY}
      streaming-chat-model:
        api-key: ${DASH_SCOPE_API_KEY}
        model-name: qwen3.5-27b

bigmodel:
  api-key: ${BIG_MODEL_API_KEY}

server:
  port: 8081
  servlet:
    context-path: /api
